#!/usr/bin/env zsh

## env setup

# include zsh_libmisc, load needed library functions
fpath=(/usr/lib/zsh_libmisc/libmisc.zwc $fpath)
autoload query_jobs
autoload revstr

# read puzzle input into variable
daythree_input=$(< input) || {
  print "Error: could not find puzzle input"
  return 1
}

# delete working dir if exist, and remake (sanitation)
[ -d /tmp/daythree_working ] && {
  rm -rf /tmp/daythree_working
}
mkdir /tmp/daythree_working

# set job count to total cpu threads + 1 if not already defined
[ -z "$j" ] && {
  j=$(($(nproc)+1))
}

# initialize worker id var
worker_id=0

# initialize worker ids arr
declare -a worker_ids

# initialize result var
result='0'

## helper functions

create_worker() {
  # initialize highest val. + workig num vars
  highest_jolt='0'
  highest_right='-1'
  working_num=''
  # reverse working num so we're reading from right -> left
  working_nums=$(revstr "$sort_me")
  while true; do
    working_num=${working_nums: :1}
    working_nums=${working_nums:1}
    [ -z "$working_num" ] && {
      print "$highest_jolt" > /tmp/daythree_working/"$worker_id"
      touch /tmp/daythree_working/"$worker_id".comp
      break
    }
    ! [ "$highest_right" = '-1' ] && {
      jolt=$((working_num*10+highest_right))
      [ "$jolt" -gt "$highest_jolt" ] && {
        highest_jolt="$jolt"
      }
    }
    [ "$working_num" -gt "$highest_right" ] && {
      highest_right="$working_num"
    }
  done
}

## main

# start workers
IFS=$'\n'
for sort_me in $=daythree_input; do
  # check active job count, wait if is greater than or equal to $j
  [ "$(query_jobs)" -ge "$j" ] && {
    until [ "$(query_jobs)" -lt "$j" ]; do
      sleep 1
    done
  }
  sort_me="$sort_me" worker_id="$worker_id" create_worker &
  worker_ids+=("$worker_id")
  worker_id=$((worker_id+1))
done
unset IFS

# wait for all workers to finish
for chk_worker in $worker_ids[@]; do
  until [ -f /tmp/daythree_working/"$chk_worker".comp ]; do
    sleep 1
  done
done

# tally up worker results
for worker_res in $worker_ids[@]; do
  do_tally=$(< /tmp/daythree_working/"$worker_res")
  result=$((result+do_tally))
done

# print result
print $result

#cleanup
rm -rf /tmp/daythree_working
