#!/usr/bin/env zsh

## env setup

# fetch puzzle input, error if 'input' not exist
dayone_input=$(<input) || {
  print "Error: could not find puzzle input"
  return 1
}

# initialize zeros counter
zeros=0

# initialize dial pointer
current_pos=50

## main

# iterate over input, using newline for field separation
IFS=$'\n'
for input_line in $=dayone_input; do
  # separate rotation direction from number of steps
  direction=${input_line: :1}
  steps=${input_line:1}

  # apply rotation
  [ "$direction" = 'R' ] && {
    (( current_pos += steps ))
  } || {
    (( current_pos -= steps ))
  }

  # normalize position within 0-99 using modulo.
  # add 100, modulo again to ensure index is positive
  (( current_pos = (current_pos % 100 + 100) % 100 ))

  # check if is pos. 0
  (( current_pos == 0 )) && {
    (( zeros++ ))
  }

done
unset IFS

# print total zeros
print $zeros
