#!/usr/bin/env zsh

## env setup

# fetch input, err if not found
daynine_input=$(<input) || {
  print "Error: could not find \'input\'"
  return 1
}

# swap hash for another char (ease of parsing)
daynine_input=${daynine_input//'#'/'K'}

# load zsh/mathfunc module for sqrt
zmodload zsh/mathfunc

# associative array for grid storage
declare -A daynine_grid

# associative array for distance storage
declare -A distances

# associative array for key of furthest corner
declare -A far_corners

## parsing steps

# move input into associative array
y_count=0
IFS=$'\n'
for line in $=daynine_input; do
  x_count=0
  ((y_count++))
  while true; do
    working=${line: :1}
    line=${line:1}
    [ -z "$working" ] && {
      break
    }
    ((x_count++))
    daynine_grid[$x_count,$y_count]=$working
  done
done
unset IFS

## helper functions

# search grid by char
search_grid() {
  [ -z "$search_char" ] && {
    search_char="$1"
  }
  dg_keys=$daynine_grid[(I)*,*]
  IFS=$' '
  for search_key in ${(@on)=dg_keys}; do
    [ "$daynine_grid[$search_key]" = "$search_char" ] && {
      print $search_key
    }
  done
  unset IFS
}

# extract y coord only from key
print_y() {
  [ -z "$key" ] && {
    y_key="$1"
  }
  firstloop=0
  IFS=$','
  for coord in $=y_key; do
    [ "$firstloop" = 1 ] && {
      print $coord
    }
    firstloop=1
  done
  unset IFS
}

# extract x coord only from key
print_x() {
  [ -z "$key" ] && {
    x_key="$1"
  }
  firstloop=0
  IFS=$','
  for coord in $=x_key; do
    [ "$firstloop" = 0 ] && {
      print $coord
    }
    firstloop=1
  done
  unset IFS
}

# calculate distance between any two corners
gib_dist() {
  [ -z "$key1" ] && {
    key1="$1"
  }
  [ -z "$key2" ] && {
    key2="$2"
  }
  y1=$(print_y "$key1")
  x1=$(print_x "$key1")
  y2=$(print_y "$key2")
  x2=$(print_x "$key2")
  integer dist
  dist=$((sqrt(((y2-y1)*(y2-y1))+((x2-x1)*(x2-x1)))))
  print $dist
}

## main

corners=$(search_grid 'K')
IFS=$'\n'
for i in $=corners; do
  for j in $=corners; do
    key2="$i" key1="$j" gib_dist
  done
done
unset IFS
