#!/usr/bin/env zsh

## env setup

# read input into variable, error if not found
dayseven_input=$(<input) || {
  print "Error: \'input\' not found"
  return 1
}

# declare associative array
declare -A dayseven_grid

# parse input line by line, read into associative array
why_count=0
IFS=$'\n'
for input_line in $=dayseven_input; do
  ((why_count++))
  eks_count=0
  while true; do
    working_indice=${input_line: :1}
    input_line=${input_line:1}
    [ -z "$working_indice" ] && {
      break
    }
    ((eks_count++))
    dayseven_grid[$why_count,$eks_count]=$working_indice
  done
done
unset IFS

# grab dayseven_grid keys
dg_keys=$dayseven_grid[(I)*,*]
first_loop=0
IFS=$' '
for key in ${(on)=dg_keys}; do
  [[ "$key" = *",1" ]] && [ "$first_loop" = 1 ] && {
    print
  }
  print -n $dayseven_grid[$key]
  first_loop=1
done
unset IFS
