#!/usr/bin/env zsh

## env setup

# read input into variable, error if not found
dayseven_input=$(<input) || {
  print "Error: \'input\' not found"
  return 1
}

# declare associative array
declare -A dayseven_grid

# parse input line by line, read into associative array
y_count=0
IFS=$'\n'
for input_line in $=dayseven_input; do
  ((y_count++))
  x_count=0
  while true; do
    working_indice=${input_line: :1}
    input_line=${input_line:1}
    [ -z "$working_indice" ] && {
      break
    }
    ((x_count++))
    dayseven_grid[$y_count,$x_count]=$working_indice
  done
done
unset IFS

# initialize result var
result=0

# initialize linear buffer
declare -a buffer

## helper functions

# search grid by char
search_grid() {
  dg_keys=$dayseven_grid[(I)*,*]
  IFS=$' '
  for key in ${(@on)=dg_keys}; do
    [ "$dayseven_grid[$key]" = "$search_char" ] && {
      print $key
    }
  done
  unset IFS
}

# extract x coord only from key
print_x() {
  firstloop=0
  IFS=$','
  for coord in $=key; do
    [ "$firstloop" = 1 ] && {
      print $coord
    }
    firstloop=1
  done
  unset IFS
}

# extract y coord only from key
print_y() {
  firstloop=0
  IFS=$','
  for coord in $=key; do
    [ "$firstloop" = 0 ] && {
      print $coord
    }
    firstloop=1
  done
  unset IFS
}

## main

# acquire starting pos.
key=$(search_char='S' search_grid)

# count first beam
buffer[$(print_x)]=1

# acquire splitter list
splitters=$(search_char='^' search_grid)

# iterate over splitters
IFS=$'\n'
for splitter in $=splitters; do
  # fetch splitter x coord
  splitter_x=$(key=$splitter print_x)
  # copy buffer[splitter] to placeholder variable
  placeholder=$buffer[$splitter_x]
  # set buffer[splitter] to zero
  buffer[$splitter_x]=0
  # set x coords to current splitter - 1
  ((splitter_x-=1))
  # copy buffer[splitter-1] to targ variable
  targ=$buffer[$splitter_x]
  # set buffer[splitter-1] to targ + placeholder
  buffer[$splitter_x]=$((targ+placeholder))
  # set x coords to current splitter + 1
  ((splitter_x+=2))
  # copy buffer[splitter+1] to targ variable
  targ=$buffer[$splitter_x]
  # set buffer[splitter+1] to targ + placeholder
  buffer[$splitter_x]=$((targ+placeholder))
done
unset IFS

# tally + print result
for res in $buffer[@]; do
  ((result+=res))
done
print $result
