#!/usr/bin/env zsh

result=0

core_var=$(./pt1_core)

IFS=$'\n'
for i in $=core_var; do
  [ "$i" != 'hit' ] && {
    print "Warn: received malformed response "$i""
  }
  ((result++))
done
unset IFS

print $result
