#!/usr/bin/env zsh

## env setup

# check for input, err if not found
[ -f input ] || {
  print "Error: 'input' not found"
  exit 1
}

# include zsh_libmisc, load needed library functions
fpath=(/usr/lib/zsh_libmisc/libmisc.zwc $fpath)
autoload query_jobs

# load zselect for extra-short sleep
zmodload zsh/zselect

# alias integer to int for brevity
alias int="integer"

# array declarations
declare -a dayeleven_input

# variable declarations
int result z_jobs is_fft is_dac

# read input into linear array
dayeleven_input=("${(@f)$(<input)}")

# initialize jobs count if unset
[ -z "$j" ] && {
  j=$(($(nproc)+1))
}

## helper functions

# recursive create_worker function
create_worker() {
  # fetch working machine
  working="$1"
  # if is fft or dac, enable that flag
  [ "$working" = fft ] && {
    is_fft=1
  }
  [ "$working" = dac ] && {
    is_dac=1
  }
  ## 1 - outbox handling
  # if we've reached out, do not recurse further
  [ "$working" = "out" ] && {
    # print 'hit' for later tallying
    ((is_dac==1)) && ((is_fft"==1)) && {
      print 'hit'
    }
    return 0
  }
  ## 2 - begin recursion (if we've reached here, we're not outbox)
  # fetch links via nested variable print
  working_links=$(eval print $"$working")
  # dead end check (if node has no definitions)
  [ -z "$working_links" ] && {
    return 0
  }
  # continue recursion for every link
  IFS=$' '
  for i in $=working_links; do
    [ "$(query_jobs)" -ge "$j" ] && {
      until [ "$(query_jobs)" -lt "$j" ]; do
        zselect -t 5
      done
    }
    is_dac=$is_dac is_fft=$is_fft create_worker "$i" &
  done
  unset IFS
  return 0
}

## parsing steps

for line in $dayeleven_input; do
  ## 1 - separate machine name and links
  # can split by char count since machine names are always 3 chars long
  machine_name=${line: :3}
  # trim 5 instead of 3 to remove ': ' from beginning of line remainder
  line=${line:5}
  ## 2 - create machine links
  IFS=$' '
  for link in $=line; do
    eval "$machine_name+=' $link'"
  done
  unset IFS
done

## main

# start create_worker recursion
create_worker you &
